# Generated by Django 5.1.7 on 2025-03-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://371bc.yeg.rac.sh/'),
        ),
    ]
