# Generated by Django 5.1.7 on 2025-03-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
