# Generated by Django 5.1.7 on 2025-03-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_author_profile_image_alter_author_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='fqid',
            field=models.URLField(blank=True, max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='fqid_encoded',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
