# Generated by Django 5.1.7 on 2025-03-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_author_display_name_alter_author_fqid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='node',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
