# Generated by Django 5.1.7 on 2025-03-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_node_api_key_remove_node_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
