# Generated by Django 5.1.7 on 2025-03-28 05:28

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_node_is_active_alter_node_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_image_url',
            field=models.URLField(blank=True, default=social.models.get_default_profile_image, max_length=5000, null=True),
        ),
    ]
