# Generated by Django 5.1.7 on 2025-03-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_author_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://35bff.yeg.rac.sh/api/'),
        ),
    ]
