# Generated by Django 5.1.7 on 2025-03-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://35bff.yeg.rac.sh/api/'),
        ),
    ]
