# Generated by Django 5.1.7 on 2025-04-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image'), ('application/base64', 'Base64 Image'), ('video/mp4', 'MP4 Video'), ('video/avi', 'AVI Video'), ('video/mov', 'MOV Video'), ('image/png', 'PNG Image')], default='text/plain', max_length=20),
        ),
    ]
