# Generated by Django 5.1.7 on 2025-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://371bc.yeg.rac.sh/api/'),
        ),
    ]
