# Generated by Django 5.1.7 on 2025-04-02 19:03

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=5000, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image_url',
            field=models.URLField(blank=True, default=social.models.get_default_profile_image, max_length=5000),
        ),
    ]
